config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'fr', to: 'pages#home-fr'
  get 'de', to: 'pages#home-de'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yenza</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js"></script>
  </head>

  <body>
    <% if current_page?(root_path) %>
      <%= render "pages/components/navbar" %>
      <%= yield %>
      <%= render "pages/components/footer" %>
    <%end%>
    <% if current_page?(fr_path) %>
      <%= render "pages/components/navbar-fr" %>
      <%= yield %>
      <%= render "pages/components/footer-fr" %>
    <%end%>
    <% if current_page?(de_path) %>
      <%= render "pages/components/navbar-de" %>
      <%= yield %>
      <%= render "pages/components/footer-de" %>
    <%end%>
  </body>
</html>

app/views/pages/components/_footer-de.html.erb
<div id="footer">
  <%# <div id="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="row footer" id="contact-footer">
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">KONTAKT</h5>
        <div class="textwidget"><p>info@yenza.io</p></div>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">ORTE</h5>
        <div class="textwidget"><p>Yenza Technologies UG</p></div>
        <div class="textwidget"><p>Veit-Stoß-str. 76 - 80687 München</p></div>
        <div class="textwidget"><p>rue des sangliers, 3 - 1170 Brussels</p></div>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">ARBEITZEIT</h5>
        <div class="textwidget"><p>Montag bis Freitag <br> 08:00 - 17:00</p></div>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/pages/components/_footer-fr.html.erb
<div id="footer">
  <%# <div id="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="row footer" id="contact-footer">
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">CONTACT</h5>
        <div class="textwidget"><p>info@yenza.io</p></div>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">BUREAUX</h5>
        <div class="textwidget"><p>Yenza Technologies UG</p></div>
        <div class="textwidget"><p>Veit-Stoß-str. 76 - 80687 München</p></div>
        <div class="textwidget"><p>rue des sangliers, 3 - 1170 Brussels</p></div>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">HEURES DE TRAVAIL</h5>
        <div class="textwidget"><p>Du Lundi au Vendredi <br> 08:00 - 17:00</p></div>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/pages/components/_footer.html.erb
<div id="footer">
  <%# <div id="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="row footer" id="contact-footer">
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">CONTACT</h5>
        <div class="textwidget"><p>info@yenza.io</p></div>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">LOCATION</h5>
        <div class="textwidget"><p>Yenza Technologies UG</p></div>
        <div class="textwidget"><p>Veit-Stoß-str. 76 - 80687 München</p></div>
        <div class="textwidget"><p>rue des sangliers, 3 - 1170 Brussels</p></div>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div id="text-3" class="widget widget_text">
        <h5 class="footer-widget-title">WORKING HOURS</h5>
        <div class="textwidget"><p>Monday to Friday <br> 08:00 - 17:00</p></div>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/pages/components/_navbar-de.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%# <%= link_to root_path do %>
    <%= image_tag("yenza_io.png", class: 'navbar-brand')%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class = "nav-link" href="#services" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Services</a>
          </li>
          <li class="nav-item active">
            <a class = "nav-link" href="#aboutme" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">About me</a>
          </li>
          <li class="nav-item">
            <a class = "nav-link" href="#contact-footer" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Contact</a>
          </li>
          <li class="nav-item">
            <a class = "nav-link" href="#nonprofit" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Non-profit</a>
          </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <div class="dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class='dropdown-item-lang'>
                <%= image_tag("de.png", class: "flag-dropdown-item") %>
                <p class='lang' >DE</p>
              </div>
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to root_path do %>
                <div class='dropdown-item-lang'>
                  <%= image_tag("us.png", class: "flag-dropdown-item") %>
                  <p class='lang' >EN</p>
                </div>
              <%end %>
              <%= link_to fr_path do %>
              <div class='dropdown-item-lang'>
                <%= image_tag("fr.png", class: "flag-dropdown-item") %>
                <p class='lang'>FR</p>
              </div>
              <%end %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/components/_navbar-fr.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%# <%= link_to root_path do %>
    <%= image_tag("yenza_io.png", class: 'navbar-brand')%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class = "nav-link" href="#services" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Services</a>
          </li>
          <li class="nav-item active">
            <a class = "nav-link" href="#aboutme" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">About me</a>
          </li>
          <li class="nav-item">
            <a class = "nav-link" href="#contact-footer" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Contact</a>
          </li>
          <li class="nav-item">
            <a class = "nav-link" href="#nonprofit" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Non-profit</a>
          </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <div class="dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class='dropdown-item-lang'>
                <%= image_tag("fr.png", class: "flag-dropdown-item") %>
                <p class='lang' >FR</p>
              </div>
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to root_path do %>
                <div class='dropdown-item-lang'>
                  <%= image_tag("us.png", class: "flag-dropdown-item") %>
                  <p class='lang' >EN</p>
                </div>
              <%end %>
              <%= link_to de_path do %>
              <div class='dropdown-item-lang'>
                <%= image_tag("de.png", class: "flag-dropdown-item") %>
                <p class='lang'>DE</p>
              </div>
              <%end %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/components/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= image_tag("yenza_io.png", class: 'navbar-brand')%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class = "nav-link" href="#services" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Services</a>
          </li>
          <li class="nav-item active">
            <a class = "nav-link" href="#aboutme" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">About me</a>
          </li>
          <li class="nav-item">
            <a class = "nav-link" href="#contact-footer" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Contact</a>
          </li>
          <li class="nav-item">
            <a class = "nav-link" href="#nonprofit" data-scroll-to-offset-value="100" data-controller="scroll-to" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Non-profit</a>
          </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <div class="dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class='dropdown-item-lang'>
                <%= image_tag("us.png", class: "flag-dropdown-item") %>
                <p class='lang' >EN</p>
              </div>
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to de_path do %>
                <div class='dropdown-item-lang'>
                  <%= image_tag("de.png", class: "flag-dropdown-item") %>
                  <p class='lang' >DE</p>
                </div>
              <%end %>
              <%= link_to fr_path do %>
              <div class='dropdown-item-lang'>
                <%= image_tag("fr.png", class: "flag-dropdown-item") %>
                <p class='lang'>FR</p>
              </div>
              <%end %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home-de.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(/assets/background-img-bn.jpg);">
  <div class="container">
    <h2 class="subheader"></h2>
    <p class="secondary-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  </div>
</div>

<div class="container">
  <div class='header-mobile'>
    <h2 class="subheader">Wir sind gleich für Sie da! Im Moment verwenden Sie bitte die englische Version</h2>
    <p class="secondary-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  </div>
  <br>
</div>

app/views/pages/home-fr.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(/assets/background-img-bn.jpg);">
  <div class="container">
    <h2 class="subheader">YENZA.IO</h2>
    <p class="secondary-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  </div>
</div>
<div class="container">
  <div class='header-mobile'>
    <h2 class="subheader">YENZA.IO</h2>
    <p class="secondary-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  </div>
  <br>

  <div class="row boxes" id="services">
    <div class="col-xs-1 col-lg-4">
      <div class="box-1 box">
        <div class='header-box'>
          <%= image_tag("data.png", class:'data-img')%>
          <h3 class='section'>Data</h3>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <br>
        <a class="button-section" href="#card-1"  data-scroll-to-offset-value="100" data-controller="scroll-to">Learn More...</a>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div class="box-2 box">
        <div class='header-box'>
          <%= image_tag("cloud.png") %>
          <h3 class='section'>Cloud</h3>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <br>
        <a class="button-section" href="#card-2"  data-scroll-to-offset-value="100" data-controller="scroll-to">Learn More...</a>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div class="box-3 box">
        <div class='header-box'>
          <%= image_tag("networking.png") %>
          <h3 class='section'>Networking</h3>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <br>
        <a class="button-section" href="#card-3"  data-scroll-to-offset-value="100" data-controller="scroll-to">Learn More...</a>
    </div>
    </div>
  </div>


  <div class='cards-info'>
    <div id="card-1">

      <h3>Data</h3>
      <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.\</p>
    </div>
    <div id="card-2">

      <h3>Cloud</h3>
      <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
    </div>
    <div id="card-3">

      <h3>Networking</h3>
      <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
    </div>
  </div>
  <div id='aboutme'>

    <h3>About me</h3>
    <div class='info'>
      <div>
        <p class="text">Michaël Berger</p>
        <p class="text">Description</p>
      </div>
      <%= image_tag("about_me_photo.png", class:'image-about') %>
    </div>
  </div>

  <div id='nonprofit'>

    <h3>Nonprofit</h3>
    <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>


  </div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(/assets/background-img-bn.jpg);">
  <div class="container">
    <h2 class="subheader">YENZA.IO</h2>
    <p class="secondary-description">Yenza provides technical services and consulting in the areas of Cloud, Data and Computer Networking.</p>
  </div>
</div>

<div class="container">
  <div class='header-mobile'>
    <h2 class="subheader">YENZA.IO</h2>
    <p class="secondary-description">Yenza provides technical services and consulting in the areas of Cloud, Data and Computer Networking.</p>
  </div>
  <br>
  <div class="row boxes" id="services">
    <div class="col-xs-1 col-lg-4">
      <div class="box-1 box">
        <%= image_tag("data.png", style:'width:65px')%>
        <h3 class='section'>Data</h3>
        <p>We will help you reveal your data! We support you through your data governance implementation, AI/ML and data analytics depolyments.</p>
        <br>
        <a class="button-section" href="#card-1"  data-scroll-to-offset-value="100" data-controller="scroll-to">Learn More...</a>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div class="box-2 box">
        <div class='header-box'>
          <%= image_tag("cloud.png", style:'width:119px') %>
          <h3 class='section'>Cloud</h3>
        </div>
        <p>We help you plan, design and implement your cloud migration or hybrid cloud and various cloud services on AWS and GCP.</p>
        <br>
        <br>
        <a class="button-section" href="#card-2"  data-scroll-to-offset-value="100" data-controller="scroll-to">Learn More...</a>
      </div>
    </div>
    <div class="col-xs-1 col-lg-4">
      <div class="box-3 box">
        <div class='header-box'>
          <%= image_tag("networking.png", style:'width:110px') %>
          <h3 class='section'>Networking</h3>
        </div>
        <p>15 years of experience in various technical roles at Cisco, now at your service.</p>
        <br>
        <br>
        <a class="button-section" href="#card-3"  data-scroll-to-offset-value="100" data-controller="scroll-to">Learn More...</a>
    </div>
    </div>
  </div>


  <div class='cards-info'>
    <div id="card-1">

      <h3>Data</h3>
      <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.\</p>
    </div>
    <div id="card-2">

      <h3>Cloud</h3>
      <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
    </div>
    <div id="card-3">

      <h3>Networking</h3>
      <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
    </div>
  </div>
  <div id='aboutme'>

    <h3>About me</h3>
    <div class='info'>
      <div>
        <p class="text">Michaël Berger</p>
        <p class="text">Description</p>
      </div>
      <%= image_tag("about_me_photo.png", class:'image-about') %>
    </div>
  </div>
  <div id='nonprofit'>
    <h3>Nonprofit</h3>
    <p class="text">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
  </div>
</div>